### PR TITLE
Bugfix: Quote hook alias :boom:

### PR DESCRIPTION
**Pull request by gabyx**
- whitespace problem

Thx for merging

### CODE REVIEW

**Comment by rycus86** [comment]
Thanks for this! Is this a problem you've seen? We have a whitespace test on Travis, I thought that should have picked it up already?

**Comment by gabyx** [comment]
Jeah on windows. We have these tests, but unfortunately not inside the `~` home folder...
had this on windows...

**Comment by rycus86** [comment]
I like your suggestion, we should try that. Travis seems to be OK with this change on Linux, so let me merge it.

**Comment by gabyx** [comment]
I have some more test changes ;-) for the `test-whitespace.sh`
Will open this in another PR, this will propery test this PR.

to what will `~` expand if it has whitespace inside?

**Comment by gabyx** [comment]
We should prohibit install into a `~` which has whitespaces. It just gives lots of troubles...
or can we really handle this properly ?

**Pull request merged**
