### PR TITLE
Windows tests. :yellow_heart:

### PR DESCRIPTION
**Pull request by gabyx**
Trying to make an appveyor test.
@rycus86 Could you enable appveyor for this repo, to be able to test this?

### CODE REVIEW

**Comment by rycus86** [comment]
Wow, this is awesome! Thanks a lot!
Let me look at AppVeyor quickly.

**Comment by gabyx** [comment]
I am not sure if the tests work, the will problably all fail :-) Have never used appveyor .-)

**Comment by gabyx** [comment]
This needs more work I guess :-), but maybe it already works. Maybe not because of `/usr/local` paths somewhere in the tests...

**Comment by rycus86** [comment]
Looks like the test setup has some issues: https://ci.appveyor.com/project/rycus86/githooks

**Comment by rycus86** [comment]
By the way, I think Travis also has Windows agents, though never really looked into them properly.

**Comment by rycus86** [comment]
And OS X 👌
https://docs.travis-ci.com/user/reference/osx/
https://docs.travis-ci.com/user/reference/windows/#git-bash

**Pull request merged**
