### PR TITLE
1: Refactor: Make githooks config variables more consistent :tada:

### PR DESCRIPTION
**Pull request by gabyx**
A **small** refactor to move global git config variables to make them more consistent.

githooks.autoupdate.updateCloneUrl -> githooks.cloneUrl
githooks.autoupdate.updateCloneBranch -> githooks.cloneBranch
githooks.previous.searchDir -> githooks.previousSearchDir

See `legacy_transformation` in `install.sh` which takes care of transformation and deleting old values.

Thanks for merging =)

### CODE REVIEW

**Comment by gabyx** [comment]
Would be good to go: All tests pass

**Comment by rycus86** [comment]
LGTM, one thing to double check before I merge, shouldn't the legacy transformation deal with `githooks.previousSearchDir` too?

**Comment by gabyx** [comment]
Thanks, ehm dont know, lets check!

**Comment by gabyx** [comment]
Updated

**Comment by rycus86** [comment]
Thanks!

**Pull request merged**
