### PR TITLE
1: Fix rules test :star:

### PR DESCRIPTION
**Pull request by gabyx**
Fix the tests/test-rule.sh

- new shfmt version
and
- new shellcheck version

### CODE REVIEW

**Comment by gabyx** [comment]
Please merge that first.

**Comment by rycus86** [comment]
This one seems to be failing the rules tests and also the corehookspath tests. Can you please check?

**Comment by gabyx** [comment]
Now it should work

**Comment by gabyx** [comment]
Everything passes except arch tests of course-> Good to go :+1:

**Pull request merged**
