### PR TITLE
Support for running Git LFS hooks :green_heart:

### PR DESCRIPTION
**Pull request by rycus86**
This is my attempt to solve #17 
@gabyx @AlexGoris-Cashforce can you please have a look?

### CODE REVIEW

**Comment by rycus86** [comment]
Unfortunately, Git LFS will still print a warning on install that the existing hook is not theirs, but otherwise should be working as far as I can tell.

**Comment by gabyx** [comment]
Nice. 
Maybe we should add a test. which without installing githooks inits a repo, and compares the output to the hook switch we are using inside base-template.

**Comment by gabyx** [comment]
> Unfortunately, Git LFS will still print a warning on install that the existing hook is not theirs, but otherwise should be working as far as I can tell.

What is the output of that?

**Comment by rycus86** [comment]
> What is the output of that?

It says:
```
$ git lfs install
Hook already exists: pre-push

        #!/bin/sh
        # Base Git hook template from https://github.com/rycus86/githooks
        #
        # It allows you to have a .githooks folder per-project that contains
        # its hooks to execute on various Git triggers.
        #
        # Version: 1907.110919-c0438b

        #####################################################
        # Execute the current hook,
        #   that in turn executes the hooks in the repo.
        #
        # Returns:
        #   0 when successfully finished, 1 otherwise
        #####################################################
        process_git_hook() {
        are_githooks_disabled && return 0
        set_main_variables
        export_staged_files
        check_for_updates_if_needed
        execute_old_hook_if_available "$@" || return 1
        execute_global_shared_hooks "$@" || return 1
        execute_local_shared_hooks "$@" || return 1
        execute_all_hooks_in "$(pwd)/.githooks" "$@" || return 1
        }

        #####################################################
        # Checks if Githooks is completely disabled
        #   for the current repository or globally.
        #   This can be done with Git config or using
        #   the ${GITH

To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.
```

**Comment by rycus86** [comment]
> Maybe we should add a test. which without installing githooks inits a repo, and compares the output to the hook switch we are using inside base-template.

You mean 1) install LFS first with its hooks, then 2) install Githooks and 3) check Githooks hooks are run with also triggers `git-lfs` ?

**Comment by gabyx** [comment]
Ah that one, ah easy. 
```git lfs install``` is done on a machine before githooks is installed. So it should be fine...

For the tests I mean:
- `git init` should install all lfs hooks (when you have done `git lfs install`
- Check the automatically installed  lfs original hooks in `.git/hooks/*`  against our function `execute_lfs_hook_if_appropriate`.
Making sure we have lfs in the same hooks as Lfs automatically installs.

**Comment by rycus86** [comment]
Oh OK, I think I see what you're saying. I'll try to have a look tomorrow/this week, time permitting. Thanks for the comments!

**Comment by gabyx** [comment]
Second test.
- `git install lfs`
- `./install.sh`
- `git init`
- `git commit`
- `check if post-commit lfs has been run` maybe moch `git-lfs` by  config: 
```ini
[alias] 
lfs = our-mock-script
```

**Comment by gabyx** [comment]
Try to add the first test case.

**Comment by rycus86** [comment]
> Try to add the first test case.

I'm also looking into this, just got it working. Will push in a minute.

**Comment by gabyx** [comment]
See two commits on the branch : https://github.com/gabyx/githooks/tree/lfs-support

**Comment by rycus86** [comment]
> See two commits on the branch : https://github.com/gabyx/githooks/tree/lfs-support

Yep, similar approach, different implementation. :)

**Comment by rycus86** [comment]
OK, added both tests now. Can you please have a look @gabyx ?
Do you have anything extra on your branch you'd want me to consider?

**Comment by gabyx** [comment]
Plz have a look at this, can we include that.
My branch commit : e6f01e9

**Comment by rycus86** [comment]
> Plz have a look at this, can we include that.
> My branch commit : [e6f01e9](https://github.com/rycus86/githooks/commit/e6f01e9b7c9ef429de4063b61afce1acdee66ad1)

Why not just have a `.githooks/pre-commit/require-lfs` and provide your own script?
I'm not against the extension, just wondering what's the added value? Less repetition? Easier setup?

**Comment by gabyx** [comment]
Ah jeah of course :). We should write a Readme, to include whats happning with LFS for the user!

**Comment by gabyx** [comment]
The PR is nice, so with that and #29 I can finally test the setup for the company wide Git Installation. Thx!

**Comment by rycus86** [comment]
> Ah jeah of course :). We should write a Readme, to include whats happning with LFS for the user!

Added #31 to track it.

**Comment by rycus86** [comment]
> Plz have a look at this, can we include that.
> My branch commit : [e6f01e9](https://github.com/rycus86/githooks/commit/e6f01e9b7c9ef429de4063b61afce1acdee66ad1)

Can you check the PR now? I added support for the `.githooks/.lfs-required` file.

**Comment by rycus86** [comment]
Sooo, bit of a complication with `.lfs-required`. Most LFS hooks are `post-*` which can't fail the operation since they run after that. So that leaves us with `pre-push`. Is that good enough to fail there?
Would you think maybe we should check elsewhere too? Like `pre-commit` ?

**Comment by gabyx** [comment]
`git lfs` hooks are:
```shell
Add the following to .git/hooks/pre-push:

        #!/bin/sh
        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, 
remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
        git lfs pre-push "$@"

Add the following to .git/hooks/post-checkout:

        #!/bin/sh
        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, 
remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
        git lfs post-checkout "$@"

Add the following to .git/hooks/post-commit:

        #!/bin/sh
        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, 
remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
        git lfs post-commit "$@"

Add the following to .git/hooks/post-merge:

        #!/bin/sh
        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, 
remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
        git lfs post-merge "$@"
```
Strange that they do not provide `git lfs pre push "$@ || exit 1`
Hm... do you know why?

**Comment by gabyx** [comment]
Maybe only fail at pre-push, yes. And print a warning for the others if something happened? Why not also `exit 1?`

**Comment by gabyx** [comment]
For me that PR looks good, merge when ever you are ready. Thx!

**Comment by rycus86** [comment]
I think it does exit with non-zero and we will too. But as https://git-scm.com/docs/githooks#_post_commit states:
> This hook is meant primarily for notification, and __cannot affect__ the outcome of git commit.

**Comment by rycus86** [comment]
I'll try to wrap this up this evening and merge it in.

**Comment by rycus86** [comment]
OK, added one more test, and will merge this once Travis is happy. Some good news: `post-checkout` fails both the initial `git clone` and also further `git checkout` if the `.githooks/.lfs-required` file is there but `git-lfs` is not found. :tada:

**Comment by gabyx** [comment]
ah perfect!

Von meinem iPhone gesendet

**Comment by gabyx** [comment]
But strange when you clone you clone the repo file `.githooks/.lfs-required` file and afterwards its fails? 

Von meinem iPhone gesendet

**Comment by gabyx** [comment]
got it :)

Von meinem iPhone gesendet

**Pull request merged**
